### ISSUE TITLE
LQPushHandler can't find referenced method setLatestEventInfo

### ISSUE THREAD

**Issue by DaleCantwell** [lqd-io/liquid-sdk-android#10]
This is the error I'm seeing:

Warning:io.lqd.sdk.LQPushHandler: can't find referenced method 'void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)' in library class android.app.Notification

In Android version 6, public void setLatestEventInfo(Context context, CharSequence contentTitle, CharSequence contentText, PendingIntent contentIntent) in android.app.Notification not longer exists. 

Instead of:
https://github.com/lqd-io/liquid-sdk-android/blob/master/liquid/src/main/java/io/lqd/sdk/LQPushHandler.java#L19

I believe it should be:
import android.support.v4.app.NotificationCompat;

And here:

https://github.com/lqd-io/liquid-sdk-android/blob/master/liquid/src/main/java/io/lqd/sdk/LQPushHandler.java#L146

Can be a NotificationCompat.Builder with all the variables "c, title, body, intent" added to the builder.
    NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder...

**Comment by letz** [comment]
Fixed with PR
